version: '3.8'
services:
  api:
    build: .
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 